name = "FiniteFields"
uuid = "bbb6641c-4b7b-4120-8cb1-379a8ed7c848"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Primes = "0.5.3, 0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
